### ISSUE TITLE
Future compatibility...

### ISSUE THREAD

**Issue by AmazingMech2418** [s2online/s2online.github.io#2]
Unfortunately, flash will be obsolete in a year, so this will only work for one year. Maybe, you could work on an HTML5 version of Scratch 2? You can just replace ActionScript code with JavaScript. Maybe you could even create full flash implementation for HTML5 canvas!

**Comment by towerofnix** [comment]
I'll quote a couple posts from the forum thread:

>I'm not aiming to replace 2.0 or create an “alternate” to 3.0 – I just want to have a way to run the plain old 2.0 editor in your browser (and to quickly open projects in it). Yeah, that means s2online won't be as useful when browsers really drop support for Flash, but that's not now.

---

>The main use of s2online is to be able to quickly run an existing project in 2.0, especially if it's incompatible with 3.0, or for any other reason. For editing projects, yeah, you're definitely better off still using the offline editor, since it can easily overwrite a file (file -> save) and has the ability to share to the website. But s2online lets you very quickly open a project in 2.0.
>
>The big case I have is, when writing GitHub issues regarding compatibility of 2.0 and 3.0, being able to include a link to s2online to share a comparison of 2.0 and 3.0. But just being able to view and run a project in the 2.0 editor is pretty handy. Also, the offline editor is only useful to people who have access to it – so, not people on Linux, nor anyone who lacks permission to download programs. So s2online works as an in-browser 2.0 editor for those people.

So TL;DR, I'm not aiming to make a competitor or alternate version of Scratch 2; I just want a way to easily run existing projects in the 2.0 editor.

**Comment by towerofnix** [comment]
To further answer your question, though... Yeah, a 2.0 remake would be pretty cool, but right now I think we're best off using 3.0 primarily. I think an interesting project would be rewriting scratch-render so that it uses canvas APIs instead of WebGL (even if that means sacrificing support/efficiency of the "graphic effect" block). That way we get all the features of 3.0 while still being compatible with systems that support WebGL. But it's just not really something I'm super interested in taking on myself. :P

**Comment by AmazingMech2418** [comment]
I think it would be useful to make a remake in HTML5 because of Flash being outdated in a year. Next year, some people couldn't even access the offline editor in some cases depending on OS updates.

**Comment by towerofnix** [comment]
Yes, that's true, and agreed! I don't think I'm the person to try doing that though. You see.. I actually really like Scratch 3.0. While I see that some people just don't like its style or block sizes or whatever, the fact is that *I do!* I enjoy making projects in Scratch 3.0 considerably more than I do using 2.0; and I know that the missing features will be re-added, the bugs ironed out. Making a 2.0-like editor (or even an entire HTML5 reimplementation of 2.0) would be a neat and useful project, but more for anyone else than for me. :P

**Comment by AmazingMech2418** [comment]
What about if there is an sb2 project that you want to stay sb2? How about hacked blocks? In order to keep something sb2, you would need it to be in a Scratch 2 editor until it is possible to convert blocks in 3.0 to 2.0. In order to use hacked blocks, you can't use 3.0.
